### PR TITLE
Autoclosing pairs improvements

### PR DESCRIPTION
**Pull request by crbelaus**
This PR adds two small improvements to autoclosing pairs both in Elixir and EEx:
- **Don't autoclose single quotes in strings and comments (Elixir).** Single quotes are commonly used in expressions as "don't", "can't", etc. so they should not be autoclosed when writing text in strings or comments.
- **Autoclose EEx tags.** It is very common to interpolate Elixir code inside EEx templates. When writing the opening `<%`, the corresponding closing `%>` tag will be automatically inserted.

### CODE REVIEW

**Comment by maxmellen** [comment]
Thanks a lot for the contribution!

Once again, I brought your changes into master, tuned the auto-closing pair configuration a little (see cc9a9fe435d0229580f91e7f4246293f5d848f4b), pulled the latest changes from `elixir-editors/elixir-tmbundle` and released an update to this extension.

Great to see your continued support 😊

**Comment by crbelaus** [comment]
Thank you for maintaining such a wonderful extension! 🙌

**Comment by crbelaus** [comment]
@maxmellen I think that [the single `<` autoclose][1] has been lost in the commit cc9a9fe.

To make it work again it should suffice to add a `{ "open": "<", "close": ">" }` line in the autoclosing pairs definition.

[1]: https://github.com/maxmellen/elixir-language-support/commit/cc9a9fe435d0229580f91e7f4246293f5d848f4b#diff-02aa21dba6601178faf9c399c935423cL18

**Comment by maxmellen** [comment]
Hey @crbelaus, I removed this auto-closing pair deliberately as I didn’t quite understand the reasoning behind it. Unless you want to write a binary literal in Elixir using `<<>>` or an EEx tag using `<%%>`, I can’t think of a scenario where you want `<` to auto-close. On the contrary, in Elixir, one will usually use `<` to mean _lesser than_ in which case, you wouldn’t want it to auto-close.

If this is something specifically for HTML tags, I don’t think this would be the right approach. This is the kind of issue I’d try to first solve in [elixir-editors/elixir-tmbundle](https://github.com/elixir-editors/elixir-tmbundle).

**Comment by crbelaus** [comment]
Sorry @maxmellen I didn't see the `<%%>` autoclosing setting and I thought it was only the `%` part :man_facepalming:

**Comment by maxmellen** [comment]
Hehe, no worries 😇

**Pull request closed without merging**
